#!/usr/bin/python3

import sys
import os

if len(sys.argv) < 2:
    which = "history"
else:
    which = sys.argv[1]
uwhich = which[0:1].upper() + which[1:]

text = open(which.upper()).read()
text = text.replace("&", "&amp;")
text = text.replace("<", "&lt;")
text = text.replace(">", "&gt;")

title = "JDBC Navigator " + uwhich

html = open(which + ".html", "w")
html.write("<html>\n"
        + "<head>\n"
        + "  <title>" + title + "</title>\n"
        + "  <style>\n"
        + "    .crumb { color: DeepPink }\n"
        + "    .crumb:link { text-decoration: none; }\n"
        + "    .crumb:visited {text-decoration: none; }\n"
        + "    .crumb:active { text-decoration: none; }\n"
        + "    .crumb:hover { text-decoration: underline; }\n"
        + "  </style>\n"
        + "</head>\n"
        + "<body>\n"
        + "<h1>" + title + "</h1>\n"
        + "<pre><a href=\"..\" class=\"crumb\">Home</a> &gt; <a href=\".\" class=\"crumb\">JDBC Navigator</a> &gt; " + uwhich + "</pre>\n"
        + "<pre>" + text + "</pre>\n"
        + "<p>\n"
        + "<a href=\".\">Go to JDBC Navigator home page</a>\n"
        + "</body>\n"
        + "</html>")
html.close()
